[package]
name = "elegant-polimi-thesis"
version = "0.1.2"
entrypoint = "src/lib.typ"
authors = ["Vittorio Robecchi <https://github.com/VictuarVi>"]
repository = "https://github.com/VictuarVi/PoliMi-PhD-Thesis"
license = "GPL-3.0-or-later"
description = "Unofficial thesis and summaries templates for the Polytechnic University of Milan."
keywords = ["polimi", "politecnico di milano", "thesis"]
categories = ["thesis", "paper"]
disciplines = ["engineering", "mathematics", "physics"]
compiler = "0.13.0"
exclude = ["*.sh", "*.pdf"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
